spring.application.name=${APP_NAME:desafio-backend}
server.port=${PORT:8080}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5432/challenge-api-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:challengeuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5783317debaa3fded50671511fd164b7}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.key.private=${JWT_PRIVATE_KEY:d2222eb1ea4ce3182d0b785d920241f5}
security.jwt.user.generator=${JWT_USER_GENERATOR:CHALLENGE-BACKEND}
